apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-access-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-access-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: all-access-role
subjects:
  - kind: ServiceAccount
    name: kubernetes-glue-operator