name: Verify Pull Request

env:
  MAVEN_ARGS: -V -ntp -e

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches: [ main ]
  workflow_dispatch:
jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'
      - name: Check code format
        run: |
          ./mvnw ${MAVEN_ARGS} formatter:validate -Dconfigfile=$PWD/contributing/eclipse-google-style.xml
          ./mvnw ${MAVEN_ARGS} impsort:check
      - name: Run unit tests
        run: ./mvnw ${MAVEN_ARGS} clean install

  build_with_integration_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
        kubernetes: [ 'v1.26.12', 'v1.27.9', 'v1.28.5' ]
    steps:
      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.10.0
        with:
          minikube version: v1.31.2
          kubernetes version: ${{ matrix.kubernetes }}
          driver: 'docker'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Run integration tests
        run: ./mvnw ${MAVEN_ARGS} clean install
