name: Release
on:
  release:
    types: [ released ]

permissions:
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ github.actor }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mvnw versions:set -DnewVersion="${RELEASE_VERSION}" versions:commit
          ./mvnw clean install -DskipTests -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true           
          ./mvnw ${MAVEN_ARGS} -q build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Set new SNAPSHOT version into pom file(s)." -a
      - name: Upload Assets
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "target/kubernetes/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.event.release.tag_name }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
