name: Release
on:
  release:
    types: [ released ]

permissions:
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'
      - name: Build
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ github.actor }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mvnw versions:set clean install versions:commit -DnewVersion="${RELEASE_VERSION}" -DskipTests -Dquarkus.container-image.build=true -Dquarkus.kubernetes.namespace=default -Dquarkus.container-image.push=true 
          ./mvnw ${MAVEN_ARGS} versions:set -DnewVersion="${RELEASE_VERSION}"
          ./mvnw ${MAVEN_ARGS} -q build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Set new SNAPSHOT version into pom files." -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
